# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Detect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x44\x65tect.proto\"$\n\rDetectRequest\x12\x13\n\x0b\x42\x61se64Image\x18\x01 \x01(\t\"$\n\x0e\x44\x65tectResponse\x12\x12\n\nJsonString\x18\x01 \x01(\t2C\n\rDetectHandler\x12\x32\n\rYOLORDetector\x12\x0e.DetectRequest\x1a\x0f.DetectResponse\"\x00\x62\x06proto3')



_DETECTREQUEST = DESCRIPTOR.message_types_by_name['DetectRequest']
_DETECTRESPONSE = DESCRIPTOR.message_types_by_name['DetectResponse']
DetectRequest = _reflection.GeneratedProtocolMessageType('DetectRequest', (_message.Message,), {
  'DESCRIPTOR' : _DETECTREQUEST,
  '__module__' : 'Detect_pb2'
  # @@protoc_insertion_point(class_scope:DetectRequest)
  })
_sym_db.RegisterMessage(DetectRequest)

DetectResponse = _reflection.GeneratedProtocolMessageType('DetectResponse', (_message.Message,), {
  'DESCRIPTOR' : _DETECTRESPONSE,
  '__module__' : 'Detect_pb2'
  # @@protoc_insertion_point(class_scope:DetectResponse)
  })
_sym_db.RegisterMessage(DetectResponse)

_DETECTHANDLER = DESCRIPTOR.services_by_name['DetectHandler']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DETECTREQUEST._serialized_start=16
  _DETECTREQUEST._serialized_end=52
  _DETECTRESPONSE._serialized_start=54
  _DETECTRESPONSE._serialized_end=90
  _DETECTHANDLER._serialized_start=92
  _DETECTHANDLER._serialized_end=159
# @@protoc_insertion_point(module_scope)
