# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Detect_pb2 as Detect__pb2


class DetectHandlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.YOLORDetector = channel.unary_unary(
                '/DetectHandler/YOLORDetector',
                request_serializer=Detect__pb2.DetectRequest.SerializeToString,
                response_deserializer=Detect__pb2.DetectResponse.FromString,
                )


class DetectHandlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def YOLORDetector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'YOLORDetector': grpc.unary_unary_rpc_method_handler(
                    servicer.YOLORDetector,
                    request_deserializer=Detect__pb2.DetectRequest.FromString,
                    response_serializer=Detect__pb2.DetectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DetectHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DetectHandler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def YOLORDetector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DetectHandler/YOLORDetector',
            Detect__pb2.DetectRequest.SerializeToString,
            Detect__pb2.DetectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
